import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import html2canvas from 'html2canvas';

/**
 * Generates a professional PDF report for Studio Model Simulation
 * @param {Object} model - The current model object
 * @param {Object} cycleStats - The calculated cycle statistics
 * @param {Object} charts - Referneces to chart DOM elements (optional)
 */
export const generatePDFReport = async (model, cycleStats, chartElementId) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;
    const today = new Date().toLocaleDateString();

    // --- TITLE PAGE ---
    doc.setFontSize(22);
    doc.setTextColor(40, 40, 40);
    doc.text("Motion Analysis Report", 14, 20);

    doc.setFontSize(12);
    doc.setTextColor(100, 100, 100);
    doc.text(`Project: ${model.name || 'Untitled Model'}`, 14, 30);
    doc.text(`Date: ${today}`, 14, 36);
    doc.text(`Generated by: MAVi Studio`, 14, 42);

    doc.setDrawColor(200, 200, 200);
    doc.line(14, 45, pageWidth - 14, 45);

    let currentY = 55;

    // --- SUMMARY STATISTICS ---
    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.text("Simulation Summary", 14, currentY);
    currentY += 10;

    if (cycleStats) {
        const statsData = [
            ['Total Cycles', cycleStats.totalCycles],
            ['Average Cycle Time', `${cycleStats.avgCycleTime.toFixed(2)}s`],
            ['VA Ratio', `${cycleStats.vaRatio}%`],
            ['Std Deviation', `${cycleStats.stdDev.toFixed(2)}s`],
            ['CV (Variability)', `${cycleStats.cv}%`]
        ];

        autoTable(doc, {
            startY: currentY,
            head: [['Metric', 'Value']],
            body: statsData,
            theme: 'striped',
            headStyles: { fillColor: [31, 41, 55] },
            styles: { fontSize: 10 }
        });

        currentY = doc.lastAutoTable.finalY + 15;
    } else {
        doc.setFontSize(10);
        doc.setTextColor(150, 150, 150);
        doc.text("No simulation data available.", 14, currentY);
        currentY += 20;
    }

    // --- CHART SNAPSHOT ---
    // If a chart element ID is provided, try to capture it
    if (chartElementId) {
        const element = document.getElementById(chartElementId);
        if (element) {
            try {
                doc.setFontSize(14);
                doc.setTextColor(0, 0, 0);
                doc.text("Cycle Time Distribution", 14, currentY);
                currentY += 10;

                const canvas = await html2canvas(element, { scale: 2 });
                const imgData = canvas.toDataURL('image/png');
                const imgWidth = pageWidth - 28;
                const imgHeight = (canvas.height * imgWidth) / canvas.width;

                if (currentY + imgHeight > doc.internal.pageSize.height - 20) {
                    doc.addPage();
                    currentY = 20;
                }

                doc.addImage(imgData, 'PNG', 14, currentY, imgWidth, imgHeight);
                currentY += imgHeight + 15;
            } catch (err) {
                console.error("Failed to capture chart:", err);
            }
        }
    }

    // --- DETAILED CYCLE HISTORY ---
    if (cycleStats && cycleStats.history.length > 0) {
        if (currentY > doc.internal.pageSize.height - 40) {
            doc.addPage();
            currentY = 20;
        }

        doc.setFontSize(16);
        doc.setTextColor(0, 0, 0);
        doc.text("Detailed Cycle Logs", 14, currentY);
        currentY += 10;

        const historyBody = cycleStats.history.map((cycle, index) => [
            index + 1,
            `${cycle.duration.toFixed(2)}s`,
            `${cycle.vaDuration.toFixed(2)}s`,
            `${((cycle.vaDuration / cycle.duration) * 100).toFixed(1)}%`,
            cycle.startTime.split('T')[1]?.split('.')[0] || '-'
        ]);

        autoTable(doc, {
            startY: currentY,
            head: [['#', 'Cycle Time', 'VA Time', 'VA %', 'Timestamp']],
            body: historyBody,
            theme: 'grid',
            headStyles: { fillColor: [37, 99, 235] },
            styles: { fontSize: 9 }
        });
    }

    // Save PDF
    doc.save(`Analysis_Report_${model.name || 'Untitled'}_${Date.now()}.pdf`);
};
